### ISSUE TITLE
NetBeans 9 crashes after the loading finished

### ISSUE THREAD

**Issue by nebrass** [Webbiefourth/Apache-Netbeans-9.0-MacOSX#1]
Hello,

Thank you for this useful tweak, I tried it but it doesn't work.
The NetBeans crashs after the loading finished. I didn't find the log to see what's happening..

Update: the only loading message shown in the splash screen, is: "Turning on modules...", then the application is closed.

When I try to run directly the netbeans executable from the bin folder, it works 100% without problem.

Please help me and thank you again !

**Comment by webbie4th** [comment]
I ran into this issue as I was experimenting with building this package shell. Thank you for running into it and reporting it! :)

Because you have tried to run the netbean app, using the Apache provided script, netbeans has already created it's "~/Library/Application Support/Netbeans/9.0". So when you ran the newly created package, it was assuming a fresh installation, that is why it crashed (I am guessing/assuming!). I was able to go into the above path, deleted directory 9.0 and ran the app again to success.

Try that. Also, in case your error is different than what I have experienced, now that you have the location of the logs (~/Library/Application Support/Netbeans/9.0/var/log) take a look and see if there is something else that you can report.

Hopefully, if this packaging technique becomes a mainstream ASF-Netbeans package, checking for unclean installation will be part of the initial launch script.

**Comment by webbie4th** [comment]
I have verified what I stated above.

After creating the new MacOS packager script for Netbeans, I ran it. Since the product has a version number (Netbeans 9.0.app) in its name, It seems that MacOS recognizes a change in the signature. When I ran the new netbeans, it crashed because netbeans.app (notice the name difference!) is the one that created the ~/Library/Application Support/Netbeans/9.0. 

I deleted that directory, and retired the manually created "netbeans.app". Now, when I delete everything and run the application, which the packager script creates, the application works fine. Restart the app again and again without crashing.

I will close this issue.
